package io.github.corvus400.fictionaldrugdiseaserefbackendkotlin.tools

import io.github.corvus400.fictionaldrugdiseaserefbackendkotlin.config.AppJson
import io.github.corvus400.fictionaldrugdiseaserefbackendkotlin.domain.disease.Disease
import io.github.corvus400.fictionaldrugdiseaserefbackendkotlin.domain.disease.DiseaseListResponse
import io.github.corvus400.fictionaldrugdiseaserefbackendkotlin.domain.drug.Drug
import io.github.corvus400.fictionaldrugdiseaserefbackendkotlin.domain.drug.DrugListResponse
import io.ktor.client.HttpClient
import io.ktor.client.engine.cio.CIO
import io.ktor.client.request.get
import io.ktor.client.statement.bodyAsText
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.writeText

fun main(args: Array<String>) = runBlocking {
    val options = SeedExportOptions.from(args = args.toList())
    HttpClient(CIO).use { client ->
        val drugs = fetchAllDrugs(client = client, baseUrl = options.baseUrl)
        val diseases = fetchAllDiseases(client = client, baseUrl = options.baseUrl)
        Files.createDirectories(options.outputDir)
        options.outputDir.resolve("V2__seed_drugs.sql").writeText(renderDrugSeed(drugs))
        options.outputDir.resolve("V3__seed_diseases.sql").writeText(renderDiseaseSeed(diseases))
    }
}

private data class SeedExportOptions(
    val baseUrl: String,
    val outputDir: Path,
) {
    companion object {
        fun from(args: List<String>): SeedExportOptions {
            val values = args.windowed(size = 2, step = 2, partialWindows = false).associate { it[0] to it[1] }
            return SeedExportOptions(
                baseUrl = values["--base-url"]?.trimEnd('/') ?: "http://localhost:8080",
                outputDir = Path.of(values["--output-dir"] ?: "src/main/resources/db/migration"),
            )
        }
    }
}

private suspend fun fetchAllDrugs(client: HttpClient, baseUrl: String): List<Drug> {
    val ids = fetchPagedIds(
        firstPage = AppJson.decodeFromString<DrugListResponse>(
            client.get("$baseUrl/v1/drugs?page=1&page_size=$SEED_PAGE_SIZE").bodyAsText(),
        ),
        pageFetcher = { page ->
            AppJson.decodeFromString<DrugListResponse>(
                client.get("$baseUrl/v1/drugs?page=$page&page_size=$SEED_PAGE_SIZE").bodyAsText(),
            )
        },
    )
    return ids.map { id ->
        AppJson.decodeFromString<Drug>(client.get("$baseUrl/v1/drugs/$id").bodyAsText())
    }
}

private suspend fun fetchAllDiseases(client: HttpClient, baseUrl: String): List<Disease> {
    val ids = fetchPagedIds(
        firstPage = AppJson.decodeFromString<DiseaseListResponse>(
            client.get("$baseUrl/v1/diseases?page=1&page_size=$SEED_PAGE_SIZE").bodyAsText(),
        ),
        pageFetcher = { page ->
            AppJson.decodeFromString<DiseaseListResponse>(
                client.get("$baseUrl/v1/diseases?page=$page&page_size=$SEED_PAGE_SIZE").bodyAsText(),
            )
        },
    )
    return ids.map { id ->
        AppJson.decodeFromString<Disease>(client.get("$baseUrl/v1/diseases/$id").bodyAsText())
    }
}

private suspend fun fetchPagedIds(
    firstPage: DrugListResponse,
    pageFetcher: suspend (Int) -> DrugListResponse,
): List<String> =
    fetchPagedIds(
        firstItems = firstPage.items.map { it.id },
        totalPages = firstPage.totalPages,
        pageFetcher = { page -> pageFetcher(page).items.map { it.id } },
    )

private suspend fun fetchPagedIds(
    firstPage: DiseaseListResponse,
    pageFetcher: suspend (Int) -> DiseaseListResponse,
): List<String> =
    fetchPagedIds(
        firstItems = firstPage.items.map { it.id },
        totalPages = firstPage.totalPages,
        pageFetcher = { page -> pageFetcher(page).items.map { it.id } },
    )

private suspend fun fetchPagedIds(
    firstItems: List<String>,
    totalPages: Int,
    pageFetcher: suspend (Int) -> List<String>,
): List<String> =
    buildList {
        addAll(firstItems)
        for (page in 2..totalPages) {
            addAll(pageFetcher(page))
        }
    }

private fun renderDrugSeed(drugs: List<Drug>): String =
    renderSeed(
        tableName = "drugs",
        rows = drugs.map { drug -> drug.id to AppJson.encodeToString(drug) },
    )

private fun renderDiseaseSeed(diseases: List<Disease>): String =
    renderSeed(
        tableName = "diseases",
        rows = diseases.map { disease -> disease.id to AppJson.encodeToString(disease) },
    )

private fun renderSeed(tableName: String, rows: List<Pair<String, String>>): String =
    buildString {
        appendLine("-- Generated by exportSeedSql. Source of truth: mock-server detail endpoints.")
        rows.forEach { (publicId, json) ->
            append("INSERT INTO ")
            append(tableName)
            append("(public_id, data) VALUES ('")
            append(publicId.sqlString())
            append("', ")
            append(DOLLAR_QUOTE)
            appendLine()
            appendLine(json)
            append(DOLLAR_QUOTE)
            appendLine("::jsonb);")
        }
    }

private fun String.sqlString(): String = replace("'", "''")

private const val SEED_PAGE_SIZE = 100
private const val DOLLAR_QUOTE = "$" + "seed_json" + "$"
